# Generated by Django 6.0.2 on 2026-02-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="language",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="price",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="trailer_id",
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.CharField(default=2.5, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(default="2h 30m", upload_to="posters/"),
            preserve_default=False,
        ),
    ]
