# Generated by Django 6.0.2 on 2026-02-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_remove_movie_language_remove_movie_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
    ]
