# Generated by Django 6.0.2 on 2026-02-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
