# Generated by Django 6.0.2 on 2026-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_movie_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="description",
        ),
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(
                blank=True,
                help_text="Paste YouTube embed URL (https://www.youtube.com/embed/...)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="movie",
            name="language",
            field=models.CharField(max_length=50),
        ),
    ]
